In [12]:
import pandas as pd
import numpy as np
import sys
import os
import re
from datetime import datetime
from google_play_scraper import app, reviews, Sort



print("Libraries loaded successfully!")

Libraries loaded successfully!

In [20]:
sys.path.append(
    os.path.abspath("..")
)

from scripts.scrap import (
    get_info,
    scrap,
    extract_columns
)

# Web scraping

In [19]:
banks = {
    "Commercial Bank of Ethiopia": "com.combanketh.mobilebanking",
    "Bank of Abyssinia": "com.boa.boaMobileBanking",
    "Dashen Bank": "com.dashen.dashensuperapp"
}
for name, app_id in banks.items():
    get_info(app_id, name)

==================================================
Commercial Bank of Ethiopia App Info
==================================================
App Title    : Commercial Bank of Ethiopia
Current Score: 4.2849674
Total Ratings: 48,295
Total Reviews: 9,307
Installs     : 5,000,000+
==================================================
Bank of Abyssinia App Info
==================================================
App Title    : BoA Mobile
Current Score: 4.3905263
Total Ratings: 9,211
Total Reviews: 1,457
Installs     : 1,000,000+
==================================================
Dashen Bank App Info
==================================================
App Title    : Dashen Bank
Current Score: 4.2336283
Total Ratings: 5,601
Total Reviews: 1,020
Installs     : 1,000,000+

In [25]:
raw_data = {}
for name, app_id in banks.items():
    result = scrap(app_id)
    extracted = extract_columns(result,name)
    raw_data[name] = extracted

for name, data in raw_data.items():
    print("=" * 50)
    print(f"{name} data")
    display(data.head())

Collected 500 raw reviews
Collected 500 raw reviews
Collected 500 raw reviews
==================================================
Commercial Bank of Ethiopia data

,review_id,review,rating,date,bank,source
0,eda74236-f7f3-4422-a139-a181e832bc27,thank you cbe,5,2026-05-13 17:16:37,Commercial Bank of Ethiopia,Google Play
1,ff53332b-2e76-46d6-83d3-f93f968a4b18,is good,5,2026-05-13 16:18:45,Commercial Bank of Ethiopia,Google Play
2,363a5616-ed3d-4274-85ee-77071067f81d,wow,5,2026-05-13 12:19:17,Commercial Bank of Ethiopia,Google Play
3,56185597-d29b-4a60-a0fb-6783638230a7,Good application,2,2026-05-13 11:27:52,Commercial Bank of Ethiopia,Google Play
4,35efe702-40c9-4e46-ad67-7574ab9ef42d,"Nice, but I can't get some recently transactio...",5,2026-05-13 11:21:48,Commercial Bank of Ethiopia,Google Play

==================================================
Bank of Abyssinia data

,review_id,review,rating,date,bank,source
0,c3bb042c-844b-4580-98b9-df418622b2fb,it's very good app,5,2026-05-12 11:50:32,Bank of Abyssinia,Google Play
1,400ce769-3726-43b2-ac4d-755b3a15f026,this app is good but the speed of app is very ...,2,2026-05-11 18:18:54,Bank of Abyssinia,Google Play
2,4d6d2f22-5e71-47be-9cde-a1cf6c9fff93,good,5,2026-05-09 14:41:50,Bank of Abyssinia,Google Play
3,e77089b3-aecf-45e2-a64a-ce917fc4233a,boa the best,5,2026-05-08 13:47:07,Bank of Abyssinia,Google Play
4,41c64c67-b81a-4326-83c4-e95044aef7f6,bank of absiniya is best bank in ethiopian,5,2026-05-07 10:33:06,Bank of Abyssinia,Google Play

==================================================
Dashen Bank data

,review_id,review,rating,date,bank,source
0,265cfda4-296c-4676-bc76-032559a65ec2,very nice app.,5,2026-05-13 17:44:57,Dashen Bank,Google Play
1,94a4413f-40c7-4842-b31c-43f70aff0686,very difficult app,1,2026-05-13 16:26:31,Dashen Bank,Google Play
2,eaeb3ab3-2f40-49c2-be8f-8d434331b7cb,"Good app, but debit transactions not allowed W...",5,2026-05-13 11:41:27,Dashen Bank,Google Play
3,24e6a87a-ec94-489c-b9e6-4ed8e33a70a9,nice,5,2026-05-13 08:15:58,Dashen Bank,Google Play
4,41170efe-a4b7-482c-83d1-fea6fa51993d,Very bad customer service line. they won't pic...,1,2026-05-12 17:33:07,Dashen Bank,Google Play

In [29]:
for name, data in raw_data.items():
    print("="*50)
    print(name)
    print(" ")
    print(f"Total reviews collected: {len(data)}")
    print(f"\nColumn dtypes:")
    print(data.dtypes)
    print("")

==================================================
Commercial Bank of Ethiopia

Total reviews collected: 500

Column dtypes:
review_id               str
review                  str
rating                int64
date         datetime64[us]
bank                    str
source                  str
dtype: object

==================================================
Bank of Abyssinia

Total reviews collected: 500

Column dtypes:
review_id               str
review                  str
rating                int64
date         datetime64[us]
bank                    str
source                  str
dtype: object

==================================================
Dashen Bank

Total reviews collected: 500

Column dtypes:
review_id               str
review                  str
rating                int64
date         datetime64[us]
bank                    str
source                  str
dtype: object

In [36]:
print("Rating distribution:")

for name, data in raw_data.items():
    print("="*50)
    print(name)
    print(" ")
    rating_counts = data['rating'].value_counts().sort_index(ascending=False)
    for rating, count in rating_counts.items():
        bar = '█' * (count // 5)
        print(f"  {int(rating)} stars: {count:>4}  {bar}")
    print("")

Rating distribution:
==================================================
Commercial Bank of Ethiopia

  5 stars:  339  ███████████████████████████████████████████████████████████████████
  4 stars:   41  ████████
  3 stars:   35  ███████
  2 stars:   12  ██
  1 stars:   73  ██████████████

==================================================
Bank of Abyssinia

  5 stars:  279  ███████████████████████████████████████████████████████
  4 stars:   37  ███████
  3 stars:   18  ███
  2 stars:   17  ███
  1 stars:  149  █████████████████████████████

==================================================
Dashen Bank

  5 stars:  322  ████████████████████████████████████████████████████████████████
  4 stars:   33  ██████
  3 stars:   27  █████
  2 stars:   19  ███
  1 stars:   99  ███████████████████

# Exploratory Data Analysis

In [37]:
print("Sample date values (raw):")

for name, data in raw_data.items():
    print("="*50)
    print(name)
    print(" ")
    print(data['date'].head(10).to_string())
    print(f"\nDate dtype: {data['date'].dtype}")
    print("")

Sample date values (raw):
==================================================
Commercial Bank of Ethiopia

0   2026-05-13 17:16:37
1   2026-05-13 16:18:45
2   2026-05-13 12:19:17
3   2026-05-13 11:27:52
4   2026-05-13 11:21:48
5   2026-05-13 11:11:25
6   2026-05-13 05:12:17
7   2026-05-12 19:02:00
8   2026-05-12 12:23:58
9   2026-05-12 06:18:40

Date dtype: datetime64[us]

==================================================
Bank of Abyssinia

0   2026-05-12 11:50:32
1   2026-05-11 18:18:54
2   2026-05-09 14:41:50
3   2026-05-08 13:47:07
4   2026-05-07 10:33:06
5   2026-05-05 11:03:08
6   2026-05-04 14:01:17
7   2026-05-03 13:40:13
8   2026-05-02 15:48:30
9   2026-05-01 09:20:45

Date dtype: datetime64[us]

==================================================
Dashen Bank

0   2026-05-13 17:44:57
1   2026-05-13 16:26:31
2   2026-05-13 11:41:27
3   2026-05-13 08:15:58
4   2026-05-12 17:33:07
5   2026-05-12 17:22:54
6   2026-05-12 16:43:12
7   2026-05-12 14:56:04
8   2026-05-12 14:29:35
9   2026-05-11 22:11:19

Date dtype: datetime64[us]

In [40]:
print("Missing Values")
for name, data in raw_data.items():
    print("="*50)
    print(name)
    print(" ")
    missing = data.isnull().sum()
    missing_pct = (missing / len(data) * 100).round(2)

    for col in data.columns:
        status = f"{missing[col]} missing ({missing_pct[col]}%)" if missing[col] > 0 else "OK"
        print(f"  {col:<15}: {status}")
    print("")

Missing Values
==================================================
Commercial Bank of Ethiopia

  review_id      : OK
  review         : OK
  rating         : OK
  date           : OK
  bank           : OK
  source         : OK

==================================================
Bank of Abyssinia

  review_id      : OK
  review         : OK
  rating         : OK
  date           : OK
  bank           : OK
  source         : OK

==================================================
Dashen Bank

  review_id      : OK
  review         : OK
  rating         : OK
  date           : OK
  bank           : OK
  source         : OK

In [42]:
print("Dupliate Values")
for name, data in raw_data.items():
    print("="*50)
    print(name)
    print(" ")

    # Exact duplicates on review text
    exact_dupes = data.duplicated(subset=['review']).sum()
    print(f"  Exact duplicate reviews : {exact_dupes}")

    # Duplicate review IDs
    id_dupes = data.duplicated(subset=['review_id']).sum()
    print(f"  Duplicate review IDs    : {id_dupes}")

    # Empty reviews 
    empty_reviews = (data['review'].str.strip() == '').sum()
    print(f"  Empty review texts      : {empty_reviews}")
    print("")

Dupliate Values
==================================================
Commercial Bank of Ethiopia

  Exact duplicate reviews : 127
  Duplicate review IDs    : 0
  Empty review texts      : 0

==================================================
Bank of Abyssinia

  Exact duplicate reviews : 89
  Duplicate review IDs    : 0
  Empty review texts      : 0

==================================================
Dashen Bank

  Exact duplicate reviews : 76
  Duplicate review IDs    : 0
  Empty review texts      : 0

In [76]:
print("Date Format")
for name, data in raw_data.items():
    print("="*50)
    print(name)
    print(" ")

    print(f"  Current dtype: {data['date'].dtype}")
    print(f"  Sample values: {data['date'].iloc[0]}")

    print(f"  Date range: {data['date'].min()} - {data['date'].max()}")
    print("")

Date Format
==================================================
Commercial Bank of Ethiopia

  Current dtype: str
  Sample values: 2026-05-13
  Date range: 2026-03-02 - 2026-05-13

==================================================
Bank of Abyssinia

  Current dtype: str
  Sample values: 2026-05-12
  Date range: 2025-02-12 - 2026-05-12

==================================================
Dashen Bank

  Current dtype: str
  Sample values: 2026-05-13
  Date range: 2025-08-13 - 2026-05-13

# Cleaning data

In [55]:
df_copy = raw_data.copy()

### Handling Missing Values
No missing values were found in all the datasets so missing values need not be handled

### Removing Duplicate Values

There are no reviews with the same id, so duplicate value handling is also not needed

### Normalizing Dates

In [56]:
for name, df in df_copy.items():
    print("="*50)
    print(name)
    print(" ")

    print("Before normalization:")
    print(df['date'].head(3).to_string())
    print(f"dtype: {df['date'].dtype}")

    df['date'] = pd.to_datetime(df['date']).dt.strftime('%Y-%m-%d')

    print("\nAfter normalization:")
    print(df['date'].head(3).to_string())
    print(f"dtype: {df['date'].dtype}")

    print(f"\nDate range: {df['date'].min()} to {df['date'].max()}")
    print("")

==================================================
Commercial Bank of Ethiopia

Before normalization:
0   2026-05-13 17:16:37
1   2026-05-13 16:18:45
2   2026-05-13 12:19:17
dtype: datetime64[us]

After normalization:
0    2026-05-13
1    2026-05-13
2    2026-05-13
dtype: str

Date range: 2026-03-02 to 2026-05-13

==================================================
Bank of Abyssinia

Before normalization:
0   2026-05-12 11:50:32
1   2026-05-11 18:18:54
2   2026-05-09 14:41:50
dtype: datetime64[us]

After normalization:
0    2026-05-12
1    2026-05-11
2    2026-05-09
dtype: str

Date range: 2025-02-12 to 2026-05-12

==================================================
Dashen Bank

Before normalization:
0   2026-05-13 17:44:57
1   2026-05-13 16:26:31
2   2026-05-13 11:41:27
dtype: datetime64[us]

After normalization:
0    2026-05-13
1    2026-05-13
2    2026-05-13
dtype: str

Date range: 2025-08-13 to 2026-05-13

### Cleaning review text

In [57]:
def clean_text(text):
        if pd.isna(text):
            return ''
        text = str(text)
        text = re.sub(r'\s+', ' ', text)  
        text = text.strip()               
        return text
for name, df in df_copy.items():
    print("="*50)
    print(name)

    df['review'] = df['review'].apply(clean_text)

    before = len(df)
    df = df[df['review'].str.len() > 0]
    removed = before - len(df)
    print(f"\nRemoved {removed} reviews that were empty after cleaning")
    print("")

==================================================
Commercial Bank of Ethiopia

Removed 0 reviews that were empty after cleaning

==================================================
Bank of Abyssinia

Removed 0 reviews that were empty after cleaning

==================================================
Dashen Bank

Removed 0 reviews that were empty after cleaning

### Validating ratings

In [58]:
for name, df in df_copy.items():
    print("="*50)
    print(name)

    invalid_ratings = df[(df['rating'] < 1) | (df['rating'] > 5)]
    print(f"Invalid ratings (outside 1–5): {len(invalid_ratings)}")

    df = df[(df['rating'] >= 1) & (df['rating'] <= 5)]

    df['rating'] = df['rating'].astype(int)

    print(f"Remaining: {len(df)} reviews")
    print(f"Rating dtype: {df['rating'].dtype}")
    print("")

==================================================
Commercial Bank of Ethiopia
Invalid ratings (outside 1–5): 0
Remaining: 500 reviews
Rating dtype: int64

==================================================
Bank of Abyssinia
Invalid ratings (outside 1–5): 0
Remaining: 500 reviews
Rating dtype: int64

==================================================
Dashen Bank
Invalid ratings (outside 1–5): 0
Remaining: 500 reviews
Rating dtype: int64

# Saving clean data

In [67]:
df_clean = {}
for name, df in df_copy.items():
    df_clean[name] = df[['review', 'rating', 'date', 'bank', 'source']].copy()
    df_clean[name] = df_clean[name].sort_values('date', ascending=False).reset_index(drop=True)
for name, df in df_clean.items():
    print(name)
    print(" ")
    print("="*100)
    display(df.head(5))

Commercial Bank of Ethiopia

====================================================================================================

,review,rating,date,bank,source
0,thank you cbe,5,2026-05-13,Commercial Bank of Ethiopia,Google Play
1,wow,5,2026-05-13,Commercial Bank of Ethiopia,Google Play
2,Good application,2,2026-05-13,Commercial Bank of Ethiopia,Google Play
3,"Nice, but I can't get some recently transactio...",5,2026-05-13,Commercial Bank of Ethiopia,Google Play
4,Very Secure but very poor interface and limite...,1,2026-05-13,Commercial Bank of Ethiopia,Google Play

Bank of Abyssinia

====================================================================================================

,review,rating,date,bank,source
0,it's very good app,5,2026-05-12,Bank of Abyssinia,Google Play
1,this app is good but the speed of app is very ...,2,2026-05-11,Bank of Abyssinia,Google Play
2,good,5,2026-05-09,Bank of Abyssinia,Google Play
3,boa the best,5,2026-05-08,Bank of Abyssinia,Google Play
4,bank of absiniya is best bank in ethiopian,5,2026-05-07,Bank of Abyssinia,Google Play

Dashen Bank

====================================================================================================

,review,rating,date,bank,source
0,very nice app.,5,2026-05-13,Dashen Bank,Google Play
1,nice,5,2026-05-13,Dashen Bank,Google Play
2,very difficult app,1,2026-05-13,Dashen Bank,Google Play
3,"Good app, but debit transactions not allowed W...",5,2026-05-13,Dashen Bank,Google Play
4,good,5,2026-05-12,Dashen Bank,Google Play

In [75]:
os.makedirs('../data/processed', exist_ok=True)
for name, df in df_clean.items():
    name = re.sub(r'\s+', '_', name) 
    output_path = f"../data/processed/{name.lower()}_reviews_clean.csv"
    df.to_csv(output_path, index=False)

    print(f"Saved to: {output_path}")

Saved to: ../data/processed/commercial_bank_of_ethiopia_reviews_clean.csv
Saved to: ../data/processed/bank_of_abyssinia_reviews_clean.csv
Saved to: ../data/processed/dashen_bank_reviews_clean.csv