In [3]:
import pandas as pd
import numpy as np
import sys
import os
import re
from datetime import datetime
from google_play_scraper import app, reviews, Sort



print("Libraries loaded successfully!")

Libraries loaded successfully!

In [4]:
sys.path.append(
    os.path.abspath("..")
)

from scripts.scrap import (
    get_info,
    scrap,
    extract_columns
)

# Web scraping

In [5]:
banks = {
    "Commercial Bank of Ethiopia": "com.combanketh.mobilebanking",
    "Bank of Abyssinia": "com.boa.boaMobileBanking",
    "Dashen Bank": "com.dashen.dashensuperapp"
}
for name, app_id in banks.items():
    get_info(app_id, name)

==================================================
Commercial Bank of Ethiopia App Info
==================================================
App Title    : Commercial Bank of Ethiopia
Current Score: 4.2865486
Total Ratings: 48,440
Total Reviews: 9,316
Installs     : 5,000,000+
==================================================
Bank of Abyssinia App Info
==================================================
App Title    : BoA Mobile
Current Score: 4.391073
Total Ratings: 9,254
Total Reviews: 1,461
Installs     : 1,000,000+
==================================================
Dashen Bank App Info
==================================================
App Title    : Dashen Bank
Current Score: 4.2612457
Total Ratings: 5,665
Total Reviews: 1,024
Installs     : 1,000,000+

In [6]:
raw_data = {}
for name, app_id in banks.items():
    result = scrap(app_id)
    extracted = extract_columns(result,name)
    raw_data[name] = extracted

for name, data in raw_data.items():
    print("=" * 50)
    print(f"{name} data")
    display(data.head())

Collected 500 raw reviews
Collected 500 raw reviews
Collected 500 raw reviews
==================================================
Commercial Bank of Ethiopia data

,review_id,review,rating,date,bank,source
0,c1e25b5d-7e79-4b60-8aa5-bed69a904f62,worst,1,2026-05-16 12:15:55,Commercial Bank of Ethiopia,Google Play
1,eb3cc438-1c10-4e72-8851-3efff6a04135,this app very full,5,2026-05-16 09:17:00,Commercial Bank of Ethiopia,Google Play
2,f8209985-ea16-4f28-bb48-d6a7276f0f08,good apps,4,2026-05-16 07:18:33,Commercial Bank of Ethiopia,Google Play
3,a983bc98-7ea7-4ac6-8fed-039ed2a7de0a,ok,5,2026-05-16 03:43:47,Commercial Bank of Ethiopia,Google Play
4,f0f249ac-ba95-4ad8-ad1d-c435693b7bf9,this update got crazy i don't know what's goin...,1,2026-05-15 23:20:32,Commercial Bank of Ethiopia,Google Play

==================================================
Bank of Abyssinia data

,review_id,review,rating,date,bank,source
0,5f69466d-ec06-4eb5-816c-296accffeff2,was Good 🙏,5,2026-05-16 00:10:06,Bank of Abyssinia,Google Play
1,f9246b8a-6688-4249-b804-0b0c5dd60590,cool,5,2026-05-15 21:07:21,Bank of Abyssinia,Google Play
2,21bcff26-5b05-485d-958f-4832ec1fac01,Its Good,5,2026-05-15 15:01:09,Bank of Abyssinia,Google Play
3,c5eb7589-59b7-4d72-8aa9-100a703ecaa3,good,5,2026-05-14 21:18:44,Bank of Abyssinia,Google Play
4,c3bb042c-844b-4580-98b9-df418622b2fb,it's very good app,5,2026-05-12 11:50:32,Bank of Abyssinia,Google Play

==================================================
Dashen Bank data

,review_id,review,rating,date,bank,source
0,12ebd51a-7912-464b-a81b-14a0aac358da,ok,5,2026-05-15 20:41:19,Dashen Bank,Google Play
1,68dd84a3-07ab-41d9-aff8-ad7916ff71a8,best app so far. thank you,5,2026-05-15 18:33:32,Dashen Bank,Google Play
2,78284116-8313-4ca8-a28c-61ce4fa44ee6,Very Annoying App i tried to open virtual bank...,1,2026-05-14 19:33:42,Dashen Bank,Google Play
3,b4a7ea95-727b-4501-8d84-77db88187c84,good,5,2026-05-14 19:26:20,Dashen Bank,Google Play
4,59a20f9e-bb87-4d5f-bee7-ce19f19baddf,good,5,2026-05-14 17:35:20,Dashen Bank,Google Play

In [7]:
for name, data in raw_data.items():
    print("="*50)
    print(name)
    print(" ")
    print(f"Total reviews collected: {len(data)}")
    print(f"\nColumn dtypes:")
    print(data.dtypes)
    print("")

==================================================
Commercial Bank of Ethiopia

Total reviews collected: 500

Column dtypes:
review_id               str
review                  str
rating                int64
date         datetime64[us]
bank                    str
source                  str
dtype: object

==================================================
Bank of Abyssinia

Total reviews collected: 500

Column dtypes:
review_id               str
review                  str
rating                int64
date         datetime64[us]
bank                    str
source                  str
dtype: object

==================================================
Dashen Bank

Total reviews collected: 500

Column dtypes:
review_id               str
review                  str
rating                int64
date         datetime64[us]
bank                    str
source                  str
dtype: object

In [8]:
print("Rating distribution:")

for name, data in raw_data.items():
    print("="*50)
    print(name)
    print(" ")
    rating_counts = data['rating'].value_counts().sort_index(ascending=False)
    for rating, count in rating_counts.items():
        bar = '█' * (count // 5)
        print(f"  {int(rating)} stars: {count:>4}  {bar}")
    print("")

Rating distribution:
==================================================
Commercial Bank of Ethiopia

  5 stars:  337  ███████████████████████████████████████████████████████████████████
  4 stars:   45  █████████
  3 stars:   33  ██████
  2 stars:   12  ██
  1 stars:   73  ██████████████

==================================================
Bank of Abyssinia

  5 stars:  281  ████████████████████████████████████████████████████████
  4 stars:   37  ███████
  3 stars:   18  ███
  2 stars:   16  ███
  1 stars:  148  █████████████████████████████

==================================================
Dashen Bank

  5 stars:  323  ████████████████████████████████████████████████████████████████
  4 stars:   33  ██████
  3 stars:   27  █████
  2 stars:   19  ███
  1 stars:   98  ███████████████████

# Exploratory Data Analysis

In [9]:
print("Sample date values (raw):")

for name, data in raw_data.items():
    print("="*50)
    print(name)
    print(" ")
    print(data['date'].head(10).to_string())
    print(f"\nDate dtype: {data['date'].dtype}")
    print("")

Sample date values (raw):
==================================================
Commercial Bank of Ethiopia

0   2026-05-16 12:15:55
1   2026-05-16 09:17:00
2   2026-05-16 07:18:33
3   2026-05-16 03:43:47
4   2026-05-15 23:20:32
5   2026-05-15 20:11:22
6   2026-05-15 19:53:26
7   2026-05-15 12:22:49
8   2026-05-15 12:07:21
9   2026-05-14 18:52:51

Date dtype: datetime64[us]

==================================================
Bank of Abyssinia

0   2026-05-16 00:10:06
1   2026-05-15 21:07:21
2   2026-05-15 15:01:09
3   2026-05-14 21:18:44
4   2026-05-12 11:50:32
5   2026-05-11 18:18:54
6   2026-05-09 14:41:50
7   2026-05-08 13:47:07
8   2026-05-07 10:33:06
9   2026-05-05 11:03:08

Date dtype: datetime64[us]

==================================================
Dashen Bank

0   2026-05-15 20:41:19
1   2026-05-15 18:33:32
2   2026-05-14 19:33:42
3   2026-05-14 19:26:20
4   2026-05-14 17:35:20
5   2026-05-14 17:29:26
6   2026-05-14 16:15:23
7   2026-05-14 15:58:59
8   2026-05-14 15:19:29
9   2026-05-13 19:14:11

Date dtype: datetime64[us]

In [10]:
print("Missing Values")
for name, data in raw_data.items():
    print("="*50)
    print(name)
    print(" ")
    missing = data.isnull().sum()
    missing_pct = (missing / len(data) * 100).round(2)

    for col in data.columns:
        status = f"{missing[col]} missing ({missing_pct[col]}%)" if missing[col] > 0 else "OK"
        print(f"  {col:<15}: {status}")
    print("")

Missing Values
==================================================
Commercial Bank of Ethiopia

  review_id      : OK
  review         : OK
  rating         : OK
  date           : OK
  bank           : OK
  source         : OK

==================================================
Bank of Abyssinia

  review_id      : OK
  review         : OK
  rating         : OK
  date           : OK
  bank           : OK
  source         : OK

==================================================
Dashen Bank

  review_id      : OK
  review         : OK
  rating         : OK
  date           : OK
  bank           : OK
  source         : OK

In [11]:
print("Dupliate Values")
for name, data in raw_data.items():
    print("="*50)
    print(name)
    print(" ")

    # Exact duplicates on review text
    exact_dupes = data.duplicated(subset=['review']).sum()
    print(f"  Exact duplicate reviews : {exact_dupes}")

    # Duplicate review IDs
    id_dupes = data.duplicated(subset=['review_id']).sum()
    print(f"  Duplicate review IDs    : {id_dupes}")

    # Empty reviews 
    empty_reviews = (data['review'].str.strip() == '').sum()
    print(f"  Empty review texts      : {empty_reviews}")
    print("")

Dupliate Values
==================================================
Commercial Bank of Ethiopia

  Exact duplicate reviews : 124
  Duplicate review IDs    : 0
  Empty review texts      : 0

==================================================
Bank of Abyssinia

  Exact duplicate reviews : 90
  Duplicate review IDs    : 0
  Empty review texts      : 0

==================================================
Dashen Bank

  Exact duplicate reviews : 76
  Duplicate review IDs    : 0
  Empty review texts      : 0

In [12]:
print("Date Format")
for name, data in raw_data.items():
    print("="*50)
    print(name)
    print(" ")

    print(f"  Current dtype: {data['date'].dtype}")
    print(f"  Sample values: {data['date'].iloc[0]}")

    print(f"  Date range: {data['date'].min()} - {data['date'].max()}")
    print("")

Date Format
==================================================
Commercial Bank of Ethiopia

  Current dtype: datetime64[us]
  Sample values: 2026-05-16 12:15:55
  Date range: 2026-03-03 23:11:02 - 2026-05-16 12:15:55

==================================================
Bank of Abyssinia

  Current dtype: datetime64[us]
  Sample values: 2026-05-16 00:10:06
  Date range: 2025-02-22 19:58:17 - 2026-05-16 00:10:06

==================================================
Dashen Bank

  Current dtype: datetime64[us]
  Sample values: 2026-05-15 20:41:19
  Date range: 2025-08-14 12:45:15 - 2026-05-15 20:41:19

# Cleaning data

In [13]:
df_copy = raw_data.copy()

### Handling Missing Values
No missing values were found in all the datasets so missing values need not be handled

### Removing Duplicate Values

There are no reviews with the same id, so duplicate value handling is also not needed

### Normalizing Dates

In [14]:
for name, df in df_copy.items():
    print("="*50)
    print(name)
    print(" ")

    print("Before normalization:")
    print(df['date'].head(3).to_string())
    print(f"dtype: {df['date'].dtype}")

    df['date'] = pd.to_datetime(df['date']).dt.strftime('%Y-%m-%d')

    print("\nAfter normalization:")
    print(df['date'].head(3).to_string())
    print(f"dtype: {df['date'].dtype}")

    print(f"\nDate range: {df['date'].min()} to {df['date'].max()}")
    print("")

==================================================
Commercial Bank of Ethiopia

Before normalization:
0   2026-05-16 12:15:55
1   2026-05-16 09:17:00
2   2026-05-16 07:18:33
dtype: datetime64[us]

After normalization:
0    2026-05-16
1    2026-05-16
2    2026-05-16
dtype: str

Date range: 2026-03-03 to 2026-05-16

==================================================
Bank of Abyssinia

Before normalization:
0   2026-05-16 00:10:06
1   2026-05-15 21:07:21
2   2026-05-15 15:01:09
dtype: datetime64[us]

After normalization:
0    2026-05-16
1    2026-05-15
2    2026-05-15
dtype: str

Date range: 2025-02-22 to 2026-05-16

==================================================
Dashen Bank

Before normalization:
0   2026-05-15 20:41:19
1   2026-05-15 18:33:32
2   2026-05-14 19:33:42
dtype: datetime64[us]

After normalization:
0    2026-05-15
1    2026-05-15
2    2026-05-14
dtype: str

Date range: 2025-08-14 to 2026-05-15

### Cleaning review text

In [15]:
def clean_text(text):
        if pd.isna(text):
            return ''
        text = str(text)
        text = re.sub(r'\s+', ' ', text)  
        text = text.strip()               
        return text
for name, df in df_copy.items():
    print("="*50)
    print(name)

    df['review'] = df['review'].apply(clean_text)

    before = len(df)
    df = df[df['review'].str.len() > 0]
    removed = before - len(df)
    print(f"\nRemoved {removed} reviews that were empty after cleaning")
    print("")

==================================================
Commercial Bank of Ethiopia

Removed 0 reviews that were empty after cleaning

==================================================
Bank of Abyssinia

Removed 0 reviews that were empty after cleaning

==================================================
Dashen Bank

Removed 0 reviews that were empty after cleaning

### Validating ratings

In [16]:
for name, df in df_copy.items():
    print("="*50)
    print(name)

    invalid_ratings = df[(df['rating'] < 1) | (df['rating'] > 5)]
    print(f"Invalid ratings (outside 1–5): {len(invalid_ratings)}")

    df = df[(df['rating'] >= 1) & (df['rating'] <= 5)]

    df['rating'] = df['rating'].astype(int)

    print(f"Remaining: {len(df)} reviews")
    print(f"Rating dtype: {df['rating'].dtype}")
    print("")

==================================================
Commercial Bank of Ethiopia
Invalid ratings (outside 1–5): 0
Remaining: 500 reviews
Rating dtype: int64

==================================================
Bank of Abyssinia
Invalid ratings (outside 1–5): 0
Remaining: 500 reviews
Rating dtype: int64

==================================================
Dashen Bank
Invalid ratings (outside 1–5): 0
Remaining: 500 reviews
Rating dtype: int64

# Saving clean data

In [19]:
df_clean = {}
for name, df in df_copy.items():
    df_clean[name] = df[['review_id', 'review', 'rating', 'date', 'bank', 'source']].copy()
    df_clean[name] = df_clean[name].sort_values('date', ascending=False).reset_index(drop=True)
for name, df in df_clean.items():
    print(name)
    print(" ")
    print("="*100)
    display(df.head(5))

Commercial Bank of Ethiopia

====================================================================================================

,review_id,review,rating,date,bank,source
0,c1e25b5d-7e79-4b60-8aa5-bed69a904f62,worst,1,2026-05-16,Commercial Bank of Ethiopia,Google Play
1,a983bc98-7ea7-4ac6-8fed-039ed2a7de0a,ok,5,2026-05-16,Commercial Bank of Ethiopia,Google Play
2,eb3cc438-1c10-4e72-8851-3efff6a04135,this app very full,5,2026-05-16,Commercial Bank of Ethiopia,Google Play
3,f8209985-ea16-4f28-bb48-d6a7276f0f08,good apps,4,2026-05-16,Commercial Bank of Ethiopia,Google Play
4,31cf1f70-1cd8-427c-9cd5-1ccb4113facf,thanks for you 😘,5,2026-05-15,Commercial Bank of Ethiopia,Google Play

Bank of Abyssinia

====================================================================================================

,review_id,review,rating,date,bank,source
0,5f69466d-ec06-4eb5-816c-296accffeff2,was Good 🙏,5,2026-05-16,Bank of Abyssinia,Google Play
1,21bcff26-5b05-485d-958f-4832ec1fac01,Its Good,5,2026-05-15,Bank of Abyssinia,Google Play
2,f9246b8a-6688-4249-b804-0b0c5dd60590,cool,5,2026-05-15,Bank of Abyssinia,Google Play
3,c5eb7589-59b7-4d72-8aa9-100a703ecaa3,good,5,2026-05-14,Bank of Abyssinia,Google Play
4,c3bb042c-844b-4580-98b9-df418622b2fb,it's very good app,5,2026-05-12,Bank of Abyssinia,Google Play

Dashen Bank

====================================================================================================

,review_id,review,rating,date,bank,source
0,12ebd51a-7912-464b-a81b-14a0aac358da,ok,5,2026-05-15,Dashen Bank,Google Play
1,68dd84a3-07ab-41d9-aff8-ad7916ff71a8,best app so far. thank you,5,2026-05-15,Dashen Bank,Google Play
2,78284116-8313-4ca8-a28c-61ce4fa44ee6,Very Annoying App i tried to open virtual bank...,1,2026-05-14,Dashen Bank,Google Play
3,105aa71e-1e72-4618-899b-78a321a5258b,good,5,2026-05-14,Dashen Bank,Google Play
4,fd76bc39-9ee1-4a56-b784-3c6e46f83d39,good and easier to used,5,2026-05-14,Dashen Bank,Google Play

In [21]:
for name, data in df_clean.items():
    print("=" * 50)
    print(f"{name} data")
    display(data.head())

==================================================
Commercial Bank of Ethiopia data

,review_id,review,rating,date,bank,source
0,c1e25b5d-7e79-4b60-8aa5-bed69a904f62,worst,1,2026-05-16,Commercial Bank of Ethiopia,Google Play
1,a983bc98-7ea7-4ac6-8fed-039ed2a7de0a,ok,5,2026-05-16,Commercial Bank of Ethiopia,Google Play
2,eb3cc438-1c10-4e72-8851-3efff6a04135,this app very full,5,2026-05-16,Commercial Bank of Ethiopia,Google Play
3,f8209985-ea16-4f28-bb48-d6a7276f0f08,good apps,4,2026-05-16,Commercial Bank of Ethiopia,Google Play
4,31cf1f70-1cd8-427c-9cd5-1ccb4113facf,thanks for you 😘,5,2026-05-15,Commercial Bank of Ethiopia,Google Play

==================================================
Bank of Abyssinia data

,review_id,review,rating,date,bank,source
0,5f69466d-ec06-4eb5-816c-296accffeff2,was Good 🙏,5,2026-05-16,Bank of Abyssinia,Google Play
1,21bcff26-5b05-485d-958f-4832ec1fac01,Its Good,5,2026-05-15,Bank of Abyssinia,Google Play
2,f9246b8a-6688-4249-b804-0b0c5dd60590,cool,5,2026-05-15,Bank of Abyssinia,Google Play
3,c5eb7589-59b7-4d72-8aa9-100a703ecaa3,good,5,2026-05-14,Bank of Abyssinia,Google Play
4,c3bb042c-844b-4580-98b9-df418622b2fb,it's very good app,5,2026-05-12,Bank of Abyssinia,Google Play

==================================================
Dashen Bank data

,review_id,review,rating,date,bank,source
0,12ebd51a-7912-464b-a81b-14a0aac358da,ok,5,2026-05-15,Dashen Bank,Google Play
1,68dd84a3-07ab-41d9-aff8-ad7916ff71a8,best app so far. thank you,5,2026-05-15,Dashen Bank,Google Play
2,78284116-8313-4ca8-a28c-61ce4fa44ee6,Very Annoying App i tried to open virtual bank...,1,2026-05-14,Dashen Bank,Google Play
3,105aa71e-1e72-4618-899b-78a321a5258b,good,5,2026-05-14,Dashen Bank,Google Play
4,fd76bc39-9ee1-4a56-b784-3c6e46f83d39,good and easier to used,5,2026-05-14,Dashen Bank,Google Play

In [22]:
os.makedirs('../data/processed', exist_ok=True)
for name, df in df_clean.items():
    name = re.sub(r'\s+', '_', name) 
    output_path = f"../data/processed/{name.lower()}_reviews_clean.csv"
    df.to_csv(output_path, index=False)

    print(f"Saved to: {output_path}")

Saved to: ../data/processed/commercial_bank_of_ethiopia_reviews_clean.csv
Saved to: ../data/processed/bank_of_abyssinia_reviews_clean.csv
Saved to: ../data/processed/dashen_bank_reviews_clean.csv