In [23]:
import pandas as pd
import sys
import os

sys.path.append(os.path.abspath(".."))

from scripts.scrap import get_info, scrap, extract_columns
from scripts.preprocess import preprocess_reviews

In [24]:
banks = {
    "Commercial Bank of Ethiopia": "com.combanketh.mobilebanking",
    "Bank of Abyssinia": "com.boa.boaMobileBanking",
    "Dashen Bank": "com.dashen.dashensuperapp"
}

## Web scraping

In [25]:
raw_data = {}

for name, app_id in banks.items():
    result = scrap(app_id)
    df = extract_columns(result, name)
    raw_data[name] = df

Collected 500 raw reviews
Collected 500 raw reviews
Collected 500 raw reviews

In [26]:
for name, df in raw_data.items():
    print(name, len(df))
    display(df.head())

Commercial Bank of Ethiopia 500

,review_id,review,rating,date,bank,source
0,92e988a8-485c-4691-90ff-4005e0f0b3b7,Please make the CBE Noor toggle to be optional...,2,2026-05-17 09:25:49,Commercial Bank of Ethiopia,Google Play
1,d7c8285b-d811-4738-ba6e-98014135b5a3,Amazing App,5,2026-05-17 04:11:07,Commercial Bank of Ethiopia,Google Play
2,850f1e2d-aae6-421d-a6b3-c9432282494e,It stopped working on its own. When you check ...,1,2026-05-16 23:44:24,Commercial Bank of Ethiopia,Google Play
3,6ee9184e-c4a8-4856-86f0-4d2566976b4c,The most backward and unstable financial app i...,1,2026-05-16 22:47:39,Commercial Bank of Ethiopia,Google Play
4,2ae8efd1-7515-4a39-a2dd-7f3e84ee190a,ok,5,2026-05-16 21:47:39,Commercial Bank of Ethiopia,Google Play

Bank of Abyssinia 500

,review_id,review,rating,date,bank,source
0,9dd3879e-2b0c-4058-8c8c-19f6b376f69c,"The worst app, also bank am begging for my own...",1,2026-05-16 12:35:22,Bank of Abyssinia,Google Play
1,5f69466d-ec06-4eb5-816c-296accffeff2,was Good 🙏,5,2026-05-16 00:10:06,Bank of Abyssinia,Google Play
2,f9246b8a-6688-4249-b804-0b0c5dd60590,cool,5,2026-05-15 21:07:21,Bank of Abyssinia,Google Play
3,21bcff26-5b05-485d-958f-4832ec1fac01,Its Good,5,2026-05-15 15:01:09,Bank of Abyssinia,Google Play
4,c5eb7589-59b7-4d72-8aa9-100a703ecaa3,good,5,2026-05-14 21:18:44,Bank of Abyssinia,Google Play

Dashen Bank 500

,review_id,review,rating,date,bank,source
0,e4c18ede-7a95-48c9-b0f8-0db83fe26191,Misguiding - Claimed anyone can convert ETB to...,1,2026-05-16 20:55:36,Dashen Bank,Google Play
1,6ccb8bab-6a2a-4048-8bf3-ea266459491e,good,5,2026-05-16 17:57:10,Dashen Bank,Google Play
2,12ebd51a-7912-464b-a81b-14a0aac358da,ok,5,2026-05-15 20:41:19,Dashen Bank,Google Play
3,68dd84a3-07ab-41d9-aff8-ad7916ff71a8,best app so far. thank you,5,2026-05-15 18:33:32,Dashen Bank,Google Play
4,78284116-8313-4ca8-a28c-61ce4fa44ee6,Very Annoying App i tried to open virtual bank...,1,2026-05-14 19:33:42,Dashen Bank,Google Play

## Cleaning data

In [27]:
clean_data = {}

for name, df in raw_data.items():
    clean_data[name] = preprocess_reviews(df)

In [28]:
for name, df in clean_data.items():
    print(name)
    display(df.head())

Commercial Bank of Ethiopia

,review_id,review,rating,date,bank,source
0,92e988a8-485c-4691-90ff-4005e0f0b3b7,Please make the CBE Noor toggle to be optional...,2,2026-05-17,Commercial Bank of Ethiopia,Google Play
1,d7c8285b-d811-4738-ba6e-98014135b5a3,Amazing App,5,2026-05-17,Commercial Bank of Ethiopia,Google Play
2,850f1e2d-aae6-421d-a6b3-c9432282494e,It stopped working on its own. When you check ...,1,2026-05-16,Commercial Bank of Ethiopia,Google Play
3,6ee9184e-c4a8-4856-86f0-4d2566976b4c,The most backward and unstable financial app i...,1,2026-05-16,Commercial Bank of Ethiopia,Google Play
4,2ae8efd1-7515-4a39-a2dd-7f3e84ee190a,ok,5,2026-05-16,Commercial Bank of Ethiopia,Google Play

Bank of Abyssinia

,review_id,review,rating,date,bank,source
0,9dd3879e-2b0c-4058-8c8c-19f6b376f69c,"The worst app, also bank am begging for my own...",1,2026-05-16,Bank of Abyssinia,Google Play
1,5f69466d-ec06-4eb5-816c-296accffeff2,was Good 🙏,5,2026-05-16,Bank of Abyssinia,Google Play
2,f9246b8a-6688-4249-b804-0b0c5dd60590,cool,5,2026-05-15,Bank of Abyssinia,Google Play
3,21bcff26-5b05-485d-958f-4832ec1fac01,Its Good,5,2026-05-15,Bank of Abyssinia,Google Play
4,c5eb7589-59b7-4d72-8aa9-100a703ecaa3,good,5,2026-05-14,Bank of Abyssinia,Google Play

Dashen Bank

,review_id,review,rating,date,bank,source
0,e4c18ede-7a95-48c9-b0f8-0db83fe26191,Misguiding - Claimed anyone can convert ETB to...,1,2026-05-16,Dashen Bank,Google Play
1,6ccb8bab-6a2a-4048-8bf3-ea266459491e,good,5,2026-05-16,Dashen Bank,Google Play
2,12ebd51a-7912-464b-a81b-14a0aac358da,ok,5,2026-05-15,Dashen Bank,Google Play
3,68dd84a3-07ab-41d9-aff8-ad7916ff71a8,best app so far. thank you,5,2026-05-15,Dashen Bank,Google Play
4,78284116-8313-4ca8-a28c-61ce4fa44ee6,Very Annoying App i tried to open virtual bank...,1,2026-05-14,Dashen Bank,Google Play

## Saving files

In [29]:
os.makedirs("../data/processed", exist_ok=True)

for name, df in clean_data.items():
    file_name = name.lower().replace(" ", "_")
    path = f"../data/processed/{file_name}_reviews_clean.csv"
    df.to_csv(path, index=False)
    print("Saved:", path)

Saved: ../data/processed/commercial_bank_of_ethiopia_reviews_clean.csv
Saved: ../data/processed/bank_of_abyssinia_reviews_clean.csv
Saved: ../data/processed/dashen_bank_reviews_clean.csv